version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name CICDtest --s3-location s3://cicd-test-20250603/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src